# This is a basic workflow to help you get started with Actions

name: RELEASE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    if: startsWith(github.event.head_commit.message, '[release]') == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Can build any Java version
    strategy:
      matrix:
        java: [ '11' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v2
      # Runs as Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Builds Maven Settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.GH_USERNAME }}",
                "password": "${{ secrets.GH_TOKEN }}"
            }]
          repositories: |
            [{
                "id": "github",
                "url": "https://maven.pkg.github.com/BananazTechnology/bot-core"
            }]
      # Runs a set of commands using the runners shell
      - name: Maven Verify
        run: mvn -V --fail-fast --no-transfer-progress --batch-mode clean package -DskipTests
      # Get POM version
      - name: Extract Maven Project Version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      # Get project name
      - name: Extract Maven Artifact ID
        run: echo ::set-output name=artifactId::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
        id: artifact
      # Get Bananaz Core version
      - name: Extract Maven Bananaz Core Version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${bananaz.version}' --non-recursive exec:exec)
        id: btCore
      #
      # Run Docker stuff
      #
      # Do stuff to build docker image          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Dockerfile and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.artifact.outputs.artifactId }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.artifact.outputs.artifactId }}:${{ steps.project.outputs.version }}
          labels: |
            tech.bananaz.app.version=${{ steps.project.outputs.version }}
            tech.bananaz.core.version=${{ steps.btCore.outputs.version }}
            tech.bananaz.maintainer=contact@bananaz.tech


