# This is a basic workflow to help you get started with Actions

name: SOFT

# Controls when the workflow will run
on: [push, workflow_dispatch]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[release]') != true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Can build any Java version
    strategy:
      matrix:
        java: [ '11' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v3
      # Runs as Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      # Print settings xml
      - name: Print settings.xml
        run: cat ~/.m2/settings.xml
      # Creates a settings.xml file for Maven
      - name: Builds Maven Settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.GH_USERNAME }}",
                "password": "${{ secrets.GH_TOKEN }}"
            }]
          repositories: |
            [{
                "id": "github",
                "url": "https://maven.pkg.github.com/BananazTechnology/bot-core"
            }]
      # Runs native Maven verify
      - name: Maven Verify
        run: mvn -V --fail-fast --no-transfer-progress --batch-mode clean verify -DskipTests
      # SonarQube analysis
      - name: Maven SonarQube Analysis
        run: mvn -V --no-transfer-progress --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}